### ISSUE TITLE
Not working with MediaWiki 1.35.1

### ISSUE THREAD

**Issue by krabina** [vonloxley/Shariff-Mediawiki#12]
After upgrading a wiki from 1.31.12 to 1.35.1 this extension seems to be broken. 

```
MediaWiki internal error.

Original exception: [YAsSpIMoiQrZWLghjAIHlQAAAAY] /index.php?title=Main_Page MWException from line 129 of includes/MagicWord.php: Error: invalid magic word 'shariffLike'
Backtrace:
#0 includes/MagicWordFactory.php(230): MagicWord->load(string)
#1 includes/parser/Parser.php(4869): MagicWordFactory->get(string)
#2 extensions/Shariff/Shariff.php(20): Parser->setFunctionHook(string, string)
#3 includes/HookContainer/HookContainer.php(320): Shariff::shariffLikeParserFunction_Setup(Parser)
#4 includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#5 includes/HookContainer/HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run(string, array)
#6 includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#7 includes/parser/Parser.php(477): Parser->firstCallInit()
#8 includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#9 includes/ServiceWiring.php(818): ParserFactory->create()
#10 vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#11 vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#12 includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#13 includes/cache/MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
#14 includes/cache/MessageCache.php(1228): MessageCache->getParser()
#15 includes/language/Message.php(1287): MessageCache->transform(string, boolean, LanguageEn, Title)
#16 includes/language/Message.php(894): Message->transformText(string)
#17 includes/language/Message.php(954): Message->toString(string)
#18 includes/OutputPage.php(944): Message->text()
#19 includes/OutputPage.php(993): OutputPage->setHTMLTitle(Message)
#20 includes/page/Article.php(662): OutputPage->setPageTitle(string)
#21 includes/actions/ViewAction.php(74): Article->view()
#22 includes/MediaWiki.php(527): ViewAction->show()
#23 includes/MediaWiki.php(313): MediaWiki->performAction(Article, Title)
#24 includes/MediaWiki.php(940): MediaWiki->performRequest()
#25 includes/MediaWiki.php(543): MediaWiki->main()
#26 index.php(53): MediaWiki->run()
#27 index.php(46): wfIndexMain()
#28 {main}

Exception caught inside exception handler: [YAsSpIMoiQrZWLghjAIHlQAAAAY] /index.php?title=Main_Page MWException from line 129 of includes/MagicWord.php: Error: invalid magic word 'shariffLike'
Backtrace:
#0 includes/MagicWordFactory.php(230): MagicWord->load(string)
#1 includes/parser/Parser.php(4869): MagicWordFactory->get(string)
#2 extensions/Shariff/Shariff.php(20): Parser->setFunctionHook(string, string)
#3 includes/HookContainer/HookContainer.php(320): Shariff::shariffLikeParserFunction_Setup(Parser)
#4 includes/HookContainer/HookContainer.php(131): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#5 includes/HookContainer/HookRunner.php(2959): MediaWiki\HookContainer\HookContainer->run(string, array)
#6 includes/parser/Parser.php(532): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit(Parser)
#7 includes/parser/Parser.php(477): Parser->firstCallInit()
#8 includes/parser/ParserFactory.php(142): Parser->__construct(MediaWiki\Config\ServiceOptions, MagicWordFactory, LanguageEn, ParserFactory, string, MediaWiki\SpecialPage\SpecialPageFactory, MediaWiki\Linker\LinkRendererFactory, NamespaceInfo, MediaWiki\Logger\LegacyLogger, MediaWiki\BadFileLookup, MediaWiki\Languages\LanguageConverterFactory, MediaWiki\HookContainer\HookContainer)
#9 includes/ServiceWiring.php(818): ParserFactory->create()
#10 vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#11 vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#12 includes/MediaWikiServices.php(1000): Wikimedia\Services\ServiceContainer->getService(string)
#13 includes/cache/MessageCache.php(1249): MediaWiki\MediaWikiServices->getParser()
#14 includes/cache/MessageCache.php(1228): MessageCache->getParser()
#15 includes/language/Message.php(1287): MessageCache->transform(string, boolean, LanguageEn, Title)
#16 includes/language/Message.php(894): Message->transformText(string)
#17 includes/language/Message.php(954): Message->toString(string)
#18 includes/OutputPage.php(944): Message->text()
#19 includes/OutputPage.php(993): OutputPage->setHTMLTitle(Message)
#20 includes/OutputPage.php(2651): OutputPage->setPageTitle(string)
#21 includes/exception/MWException.php(179): OutputPage->prepareErrorPage(string)
#22 includes/exception/MWException.php(231): MWException->reportHTML()
#23 includes/exception/MWExceptionHandler.php(104): MWException->report()
#24 includes/exception/MWExceptionHandler.php(185): MWExceptionHandler::report(MWException)
#25 includes/MediaWiki.php(576): MWExceptionHandler::handleException(MWException, string)
#26 index.php(53): MediaWiki->run()
#27 index.php(46): wfIndexMain()
#28 {main}
```

**Comment by vonloxley** [comment]
Thanks. I plan to migrate to 1.35.x in the next months and will have a look at this then.

**Comment by krabina** [comment]
Any news?
