### ISSUE TITLE
Error in MW 1.31

### ISSUE THREAD

**Issue by krabina** [vonloxley/Shariff-Mediawiki#13]
I just tried the latest version of Shariff in MW 1.31 and recieved an error:
```
[YKfkhfeB8fYUoh6PIwE-HwAAAAc] /Special:Version Error from line 17 of /extensions/Shariff/Shariff.php: Call to undefined method MediaWiki\MediaWikiServices::getContentLanguage()

Backtrace:

#0 /includes/Hooks.php(177): Shariff::shariffLikeParserFunction_Setup(Parser)
#1/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#2 /includes/parser/Parser.php(336): Hooks::run(string, array)
#3 /includes/StubObject.php(112): Parser->firstCallInit()
#4 /includes/StubObject.php(138): StubObject->_call(string, array)
#5 /includes/cache/MessageCache.php(1105): StubObject->__call(string, array)
#6 /includes/cache/MessageCache.php(1081): MessageCache->getParser()
#7 /includes/Message.php(1273): MessageCache->transform(string, boolean, LanguageEn, Title)
#8 /includes/Message.php(874): Message->transformText(string)
#9 /includes/Message.php(934): Message->toString(string)
#10 /includes/OutputPage.php(902): Message->text()
#11 /includes/OutputPage.php(949): OutputPage->setHTMLTitle(Message)
#12 /includes/specialpage/SpecialPage.php(531): OutputPage->setPageTitle(string)
#13 /includes/specials/SpecialVersion.php(52): SpecialPage->setHeaders()
#14 /includes/specialpage/SpecialPage.php(565): SpecialVersion->execute(NULL)
#15 /includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#16 /includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#17 /includes/MediaWiki.php(818): MediaWiki->performRequest()
#18 /includes/MediaWiki.php(524): MediaWiki->main()
#19 index.php(42): MediaWiki->run()
#20 {main}
```
Is the latest version not compatible with MW 1.31 anymore?

**Comment by hexmode** [comment]
Seems to work in 1.35 and 1.31 is no longer supported, so I think this is fine.

**Comment by vonloxley** [comment]
1.31 is no longer maintained, so I concentrate on 1.35.
